main: net.obnoxint.mcdev.ProperTime.ProperTime
name: ProperTime
version: 2.1-omc

author: obnoxint
email: mail@obnoxint.net
authors: [obnoxint, andersonhc]



softdepend: [MultiVerse, multiverse-core]